opam-version: "1"
version: "3.09.1"
src: "http://web.archive.org/web/20120209151915/www.metaocaml.org/dist/old/MetaOCaml_309_alpha_030.tar.gz"
build: [
  ["./configure" "-prefix" prefix]
  [make "world"]
  [make "install"]
  ["mkdir" "-p" "%{prefix}%/lib/ocaml/compiler-libs"]
  ["cp" "-r" "typing" "parsing" "utils" "%{prefix}%/lib/ocaml/compiler-libs/"]
]
packages: [
  "base-unix"
  "base-bigarray"
  "base-threads"
]
env: [[CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]]
