opam-version: "1"
version: "4.01.0"
src: "http://caml.inria.fr/pub/distrib/ocaml-4.01/ocaml-4.01.0.tar.gz"
build: [
  ["./configure" "-prefix" prefix "-with-debug-runtime"
    "-cc" "musl-gcc -Os"
    "-aspp" "musl-gcc -c"
    "-libs" "-static"
    "-no-tk" "-no-curses" "-no-graph"
    "-no-shared-libs"
    ]
  [make "world.opt"]
  [make "install"]
]
packages: [
  "base-unix"
  "base-bigarray"
  "base-threads"
  "base-ocamlbuild"
]
env: [[CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]]
