opam-version: "1"
version: "4.03.0"
src: "https://github.com/ocaml/ocaml/archive/4.03.0.tar.gz"
build: [
  ["sh" "./configure" "-prefix" prefix "-with-debug-runtime"]
  [make "world"]
  [make "world.opt"]
  [make "install"]
]
patches: [ "http://ygrek.org.ua/files/ocaml-4.03.0+termux.patch" ]
packages: [
  "base-unix"
  "base-bigarray"
  "base-threads"
]
env: [[CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]]
