opam-version: "1"
version: "4.02.1"
src: "https://github.com/metaocaml/ber-metaocaml/archive/ber-n102.tar.gz"
build: [
  ["./configure" "-prefix" "%{prefix}%"]
  ["%{make}%" "world" "bootstrap" "opt" "opt.opt"]
  ["%{make}%" "-i" "install"]
  ["%{make}%" "-C" "metalib" "all" "install"]
]
packages : [ "base-unix" "base-bigarray" "base-threads" "base-ocamlbuild" "base-metaocaml-ocamlfind"]
env: [
  [ CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs" ]
]
