name: Install OCaml
inputs:
  compiler:
    required: true
runs:
  using: composite
  steps:
    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ inputs.compiler }}
        opam-disable-sandboxing: true
        opam-repositories: |
          default: file://.
