The following actions will be performed:
  ↻  recompile oqamldebug 0.9.5

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
⊘  removed   oqamldebug.0.9.5
[oqamldebug: qmake oqamldebug.pro] Command started
+ qmake "CONFIG-=app_bundle" "CONFIG+=release" "PREFIX_BIN=/home/berenger/.opam/4.02.3/bin/" "CONFIG-=debug" "LIBS+=-lX11" "oqamldebug.pro" (CWD=/home/berenger/.opam/4.02.3/build/oqamldebug.0.9.5)
[oqamldebug: make] Command started
+ make  (CWD=/home/berenger/.opam/4.02.3/build/oqamldebug.0.9.5)
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o main.o main.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o arguments.o arguments.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o textdiff.o textdiff.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o ocamlrun.o ocamlrun.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o ocamlbreakpoint.o ocamlbreakpoint.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o ocamlstack.o ocamlstack.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o ocamlsourcehighlighter.o ocamlsourcehighlighter.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o ocamldebughighlighter.o ocamldebughighlighter.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o filesystemwatcher.o filesystemwatcher.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o ocamlwatch.o ocamlwatch.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o ocamldebug.o ocamldebug.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o mainwindow.o mainwindow.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o options.o options.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o ocamlsource.o ocamlsource.cpp
- /usr/lib/x86_64-linux-gnu/qt4/bin/moc -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. mainwindow.h -o moc_mainwindow.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o moc_mainwindow.o moc_mainwindow.cpp
- /usr/lib/x86_64-linux-gnu/qt4/bin/moc -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. ocamlsourcehighlighter.h -o moc_ocamlsourcehighlighter.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o moc_ocamlsourcehighlighter.o moc_ocamlsourcehighlighter.cpp
- /usr/lib/x86_64-linux-gnu/qt4/bin/moc -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. ocamldebughighlighter.h -o moc_ocamldebughighlighter.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o moc_ocamldebughighlighter.o moc_ocamldebughighlighter.cpp
- /usr/lib/x86_64-linux-gnu/qt4/bin/moc -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. ocamldebug.h -o moc_ocamldebug.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o moc_ocamldebug.o moc_ocamldebug.cpp
- /usr/lib/x86_64-linux-gnu/qt4/bin/moc -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. ocamlwatch.h -o moc_ocamlwatch.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o moc_ocamlwatch.o moc_ocamlwatch.cpp
- /usr/lib/x86_64-linux-gnu/qt4/bin/moc -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. ocamlstack.h -o moc_ocamlstack.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o moc_ocamlstack.o moc_ocamlstack.cpp
- /usr/lib/x86_64-linux-gnu/qt4/bin/moc -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. ocamlrun.h -o moc_ocamlrun.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o moc_ocamlrun.o moc_ocamlrun.cpp
- /usr/lib/x86_64-linux-gnu/qt4/bin/moc -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. ocamlbreakpoint.h -o moc_ocamlbreakpoint.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o moc_ocamlbreakpoint.o moc_ocamlbreakpoint.cpp
- /usr/lib/x86_64-linux-gnu/qt4/bin/moc -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. filesystemwatcher.h -o moc_filesystemwatcher.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o moc_filesystemwatcher.o moc_filesystemwatcher.cpp
- /usr/lib/x86_64-linux-gnu/qt4/bin/moc -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. ocamlsource.h -o moc_ocamlsource.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o moc_ocamlsource.o moc_ocamlsource.cpp
- /usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name oqamldebug oqamldebug.qrc -o qrc_oqamldebug.cpp
- g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=\"0.9.5\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o qrc_oqamldebug.o qrc_oqamldebug.cpp
- g++ -m64 -Wl,-O1 -o oqamldebug main.o arguments.o textdiff.o ocamlrun.o ocamlbreakpoint.o ocamlstack.o ocamlsourcehighlighter.o ocamldebughighlighter.o filesystemwatcher.o ocamlwatch.o ocamldebug.o mainwindow.o options.o ocamlsource.o moc_mainwindow.o moc_ocamlsourcehighlighter.o moc_ocamldebughighlighter.o moc_ocamldebug.o moc_ocamlwatch.o moc_ocamlstack.o moc_ocamlrun.o moc_ocamlbreakpoint.o moc_filesystemwatcher.o moc_ocamlsource.o qrc_oqamldebug.o    -L/usr/lib/x86_64-linux-gnu -lX11 -lQtGui -lQtNetwork -lQtCore -lpthread 
[oqamldebug: strip oqamldebug] Command started
+ strip "oqamldebug" (CWD=/home/berenger/.opam/4.02.3/build/oqamldebug.0.9.5)
∗  installed oqamldebug.0.9.5
Done.
