opam-version: "1"
name: "3.12.1"
src: "http://caml.inria.fr/pub/distrib/ocaml-3.12/ocaml-3.12.1.tar.gz"
build: [
  ["./configure" "-prefix" "%{prefix}%"]
  ["%{make}%" "world"]
  ["%{make}%" "world.opt"]
  ["%{make}%" "install"]
  ["mkdir" "-p" "%{prefix}%/lib/ocaml/compiler-libs"]
  ["cp" "-r" "typing" "parsing" "utils" "%{prefix}%/lib/ocaml/compiler-libs/"]
]
packages: ["base-unix" "base-bigarray" "base-threads"]
env: [
  [CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]
]
preinstalled: false
