opam-version: "1"
name: "4.01.0dev+endian"
src: "https://github.com/avsm/ocaml/archive/avsm+ocp-endian.tar.gz"
build: [
  ["./configure" "-prefix" "%{prefix}%" "-with-debug-runtime"]
  ["%{make}%" "world"]
  ["%{make}%" "world.opt"]
  ["%{make}%" "install"]
  ["sh" "-c" "rm %{lib}%/ocaml/bigarray.*"]
]
packages: ["lwt" "ocamlfind" "xenbigarray"]
env: [
  [MIRAGE_OS = "xen"]
  [MIRAGE_NET = "direct"]
]
