opam-version: "1"
version: "4.04.0+afl"
src: "https://github.com/stedolan/ocaml/archive/afl-backport.tar.gz"
build: [
  ["mkdir" "-p" "%{lib}%/ocaml/"]
  ["sh" "-exc" "echo \"* : g = 1\" > %{lib}%/ocaml/ocaml_compiler_internal_params"]
  ["./configure" "-prefix" prefix]
  [make "world"]
  [make "world.opt"]
  [make "install"]
]
packages: [
  "base-unix"
  "base-bigarray"
  "base-threads"
]
env: [[CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]]
