opam-version: "1"
version: "4.00.1"
src: "http://caml.inria.fr/pub/distrib/ocaml-4.00/ocaml-4.00.1.tar.bz2"
patches: ["https://bitbucket.org/camlspotter/spotinstall/raw/26c014770721e44be11f364f09b149cff54a047f/ocaml-annot-4.00.1.patch"]
make: [
  "world"
  "world.opt"
]
packages: [
  "base-unix"
  "base-bigarray"
  "base-threads"
  "base-ocamlbuild"
]
env: [[CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]]
