name: Install Package
inputs:
  opam:
    required: true
  package:
    required: true
  env:
    default: '{}'
runs:
  using: composite
  steps:
    - name: Get opam cli option
      id: cli
      shell: sh
      run: |
        if [ "${{ inputs.opam }}" = "opam-2.1" ]; then
          echo 'cli=--cli=2.1 --confirm-level=unsafe-yes' >> $GITHUB_OUTPUT
        fi
    - name: Install ${{ inputs.package }} depopts
      if: inputs.opam == 'opam-2.0'
      shell: sh
      run: |
        opam depext ${{ inputs.package }}
    - name: Install ${{ inputs.package }}
      shell: sh
      env: ${{ fromJson(inputs.env) }}
      run: |
        opam install --deps-only ${{ steps.cli.outputs.cli }} ${{ inputs.package }}
        opam install ${{ steps.cli.outputs.cli }} ${{ inputs.package }}
        opam remove ${{ steps.cli.outputs.cli }} ${{ inputs.package }}
