lib: [
  (* Re *)
  "_build/lib/re.cma"
  "_build/lib/re.cmi"
  "_build/lib/re.cmxa"
  "_build/lib/re.a"

  (* Re_perl *)
  "_build/lib/re_perl.cma"
  "_build/lib/re_perl.cmi"
  "_build/lib/re_perl.cmxa"
  "_build/lib/re_perl.a"

  (* Re_emacs *)
  "_build/lib/re_emacs.cma"
  "_build/lib/re_emacs.cmi"
  "_build/lib/re_emacs.cmxa"
  "_build/lib/re_emacs.a"

  (* Re_glob *)
  "_build/lib/re_glob.cma"
  "_build/lib/re_glob.cmi"
  "_build/lib/re_glob.cmxa"
  "_build/lib/re_glob.a"

  (* Re_posix *)
  "_build/lib/re_posix.cma"
  "_build/lib/re_posix.cmi"
  "_build/lib/re_posix.cmxa"
  "_build/lib/re_posix.a"

  (* Re_glob *)
  "_build/lib/re_str.cma"
  "_build/lib/re_str.cmi"
  "_build/lib/re_str.cmxa"
  "_build/lib/re_str.a"

  (* cmis *)
  "_build/lib/automata.cmi"
  "_build/lib/pcre.cmi"
  "_build/lib/re_emacs.cmi"
  "_build/lib/re_perl.cmi"
  "_build/lib/pcre.cmi"
  "_build/lib/re_str.cmi"
  "_build/lib/cset.cmi"
  "_build/lib/re.cmi"
  "_build/lib/re_glob.cmi"
  "_build/lib/re_posix.cmi"
]
