bin: [

  "_obuild/opam/opam.asm" { "opam" }

  (* rsync scripts *)
  "_obuild/opam-rsync-init/opam-rsync-init.asm" { "opam-rsync-init" }
  "_obuild/opam-rsync-update/opam-rsync-update.asm" { "opam-rsync-update" }
  "_obuild/opam-rsync-download/opam-rsync-download.asm" { "opam-rsync-download" }
  "_obuild/opam-rsync-upload/opam-rsync-upload.asm" { "opam-rsync-upload" }
 
  (* server scripts *)
  "_obuild/opam-server/opam-server.asm" { "opam-server" }
  "_obuild/opam-server-init/opam-server-init.asm" { "opam-server-init" }
  "_obuild/opam-server-update/opam-server-update.asm" { "opam-server-update" }
  "_obuild/opam-server-download/opam-server-download.asm" { "opam-server-download" }
  "_obuild/opam-server-upload/opam-server-upload.asm" { "opam-server-upload" }
 
  (* git scripts *)
  "_obuild/opam-git-init/opam-git-init.asm" { "opam-git-init" }
  "_obuild/opam-git-update/opam-git-update.asm" { "opam-git-update" }
  "_obuild/opam-git-download/opam-git-download.asm" { "opam-git-download" }
  "_obuild/opam-git-upload/opam-git-upload.asm" { "opam-git-upload" }
 
  (* helper scripts *)
  "_obuild/opam-mk-install/opam-mk-install.asm" { "opam-mk-install" }
  "_obuild/opam-mk-config/opam-mk-config.asm" { "opam-mk-config" }
  "_obuild/opam-mk-repo/opam-mk-repo.asm" { "opam-mk-repo" }

]
