opam-version: "1"
version: "4.03.0+beta2+flambda"
src: "https://github.com/ocaml/ocaml/tarball/4.03.0+beta2"
build: [
  ["mkdir" "-p" "%{lib}%/ocaml/"]
  ["sh" "-exc" "echo \"* : g = 1\" > %{lib}%/ocaml/ocaml_compiler_internal_params"]
  ["./configure" "-prefix" prefix "-with-debug-runtime" "-flambda"]
  [make "world"]
  [make "world.opt"]
  [make "install"]
]
packages: [
  "base-unix"
  "base-bigarray"
  "base-threads"
]
env: [[CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]]
