opam-version: "1"
version: "4.00.1"
src: "https://github.com/metaocaml/ber-metaocaml/archive/ber-N100.tar.gz"
build: [
  ["./configure" "-prefix" prefix "-no-tk"]
  [make "-C" "metalib" "patch"]
  [make "core"]
  [make "coreboot"]
  [make "all"]
  [make "-i" "install"]
  [make "-C" "metalib" "all"]
  [make "-C" "metalib" "install"]
]
packages: [
  "base-unix"
  "base-bigarray"
  "base-threads"
  "base-ocamlbuild"
]
env: [[CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]]
