opam-version: "1"
version: "4.00.1"
src: "http://caml.inria.fr/pub/distrib/ocaml-4.00/ocaml-4.00.1.tar.gz"
patches: [
  "https://raw.githubusercontent.com/ocaml/opam-repository/master/compilers/4.00.1/4.00.1/fix-clang-build-on-osx.diff"
]
make: [
  "world"
  "opt"
  "opt.opt"
]
packages: [
  "base-unix"
  "base-bigarray"
  "base-threads"
  "base-ocamlbuild"
]
env: [[CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]]
