opam-version: "1"
version: "4.01.0"
src: "http://caml.inria.fr/pub/distrib/ocaml-4.01/ocaml-4.01.0.tar.gz"
patches:["https://github.com/andrewray/mirage-fpga/releases/download/v0.1/freebsd10-armv6-natdynlink.patch"]
build: [
  ["./configure" "-prefix" prefix]
  [make "world"]
  [make "world.opt"]
  [make "install"]
]
packages: [
  "base-unix"
  "base-bigarray"
  "base-threads"
  "base-ocamlbuild"
]
env: [[CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]]
