install "coq" {
  bin = [
    [ "bin/coqc" ];
    [ "bin/coqchk" ];
    [ "bin/coqchk.byte" ];
    [ "bin/coqchk.opt" ];
    [ "bin/coqc.opt" ];
    [ "bin/coqdep" ];
    [ "bin/coqdep_boot" ];
    [ "bin/coqdoc" ];
    [ "bin/coq_makefile" ];
    [ "bin/coqmktop" ];
    [ "bin/coqmktop.opt" ];
    [ "bin/coq-tex" ];
    [ "bin/coqtop" ];
    [ "bin/coqtop.byte" ];
    [ "bin/coqtop.opt" ];
    [ "bin/coqwc" ];
    [ "bin/gallina" ];
  ]
}