opam-version: "1"
version: "3.08.2"
src: "http://caml.inria.fr/pub/distrib/ocaml-3.08/ocaml-3.08.2.tar.gz"
build: [
  ["./configure" "-prefix" prefix]
  [make "world"]
  [make "world.opt"]
  [make "install"]
  ["mkdir" "-p" "%{prefix}%/lib/ocaml/compiler-libs"]
  ["cp" "-r" "typing" "parsing" "utils" "%{prefix}%/lib/ocaml/compiler-libs/"]
]
packages: [
  "base-unix"
  "base-bigarray"
  "base-threads"
  "base-ocamlbuild"
]
env: [[CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]]
