opam-version: "1"
version: "4.04.0"
src: "https://github.com/chambart/ocaml-1/archive/lto.tar.gz"
build: [
  ["./configure" "-prefix" prefix "-with-debug-runtime" "-flambda"]
  ["sh" "-exc" "echo \"* : lto = 1\" > %{lib}%/ocaml/ocaml_compiler_internal_params"]
  [make "world"]
  [make "world.opt"]
  [make "install"]
]
packages: [ "base-unix" "base-bigarray" "base-threads" ]
env: [[CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]]
