opam-version: "1"
version: "4.02.1"
src: "https://github.com/yallop/ocaml/archive/modular-implicits-ber.tar.gz"
build: [
  ["./configure" "-prefix" "%{prefix}%"]
  ["%{make}%" "world" "opt" "opt.opt"]
  ["%{make}%" "install"]
  ["%{make}%" "-C" "metalib" "all" "install"]
]
packages: ["base-unix" "base-bigarray" "base-threads" "base-ocamlbuild" "base-metaocaml-ocamlfind"]
env: [
  [CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]
]
