opam-version: "1"
version: "4.02.1"
src: "http://caml.inria.fr/pub/distrib/ocaml-4.02/ocaml-4.02.1.tar.gz"
build: [
  ["./configure" "-prefix" prefix "-with-debug-runtime" "-cc" "gcc -m32" "-as" "as --32" "-aspp" "gcc -m32 -c" "-host" "i386-linux" "-partialld"
"ld -r -melf_i386"]
  [make "world"]
  [make "world.opt"]
  [make "install"]
]
packages: [
  "base-unix"
  "base-bigarray"
  "base-threads"
]
env: [[CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]]
